name: Docker Image CI
on:
  push:
    branches:
        - domestic
jobs:
  build:
    runs-on: ubuntu-latest
    steps:            
      - uses: actions/checkout@v4
      - name: Run the Action
        uses: gacts/run-and-post-run@v1
        with:
          run: |
            docker version
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ secrets.DOCKER_URL }}
            cd ${{ github.workspace }}
            ls
            docker build -t ${{ secrets.DOCKER_URL }}/jawbts/jawbts-api-domestic:latest .
            docker push ${{ secrets.DOCKER_URL }}/jawbts/jawbts-api-domestic:latest
          post: docker logout ${{ secrets.DOCKER_URL }}